### ISSUE TITLE
Preparare la struttura base della homepage

### ISSUE THREAD

**Issue by totarochristian** [MarcoBione/hungry-frontoffice#2]

**Comment by MarcoBione** [comment]
Assegnata la issue ad Andrea

Apertura Branch:
git fetch origin
git checkout 2-preparare-la-struttura-base-della-homepage

**Comment by AndreaCollura** [comment]
- fatta struttura home page + stile 
- convertiti gli elementi statici in componenti
- aggiunte media queries
