### ISSUE TITLE
Sistemare la sezione dei ristoranti di tendenza

### ISSUE THREAD

**Issue by totarochristian** [MarcoBione/hungry-frontoffice#21]
I ristoranti di tendenza possono essere:
- 3 a caso
- i primi tre
- gli ultimi tre
- selezionati in base al numero di ordini per ognuno di loro (questo richiede modifiche backend)

Bisogna scegleire una di queste opzioni e implementarla.

**Comment by MarcoBione** [comment]
Branch aperto:

git fetch origin
git checkout 21-sistemare-la-sezione-dei-ristoranti-di-tendenza

**Comment by totarochristian** [comment]
Nei ristoranti di tendenza sarebbe da togliere il pulsante mostra altro perchè al momento non ha senso visto che non fa nulla.

**Comment by MarcoBione** [comment]
Spliceeee!!! il numero di iterazioni per lo stampo delle carte dei ristoranti è stato bloccato a solo 3 carte, le prime dell'array ottenuto dopo la chiamata axios
