### ISSUE TITLE
Realizzare carrello

### ISSUE THREAD

**Issue by totarochristian** [MarcoBione/hungry-frontoffice#26]
Realizzare la gestione del carrello.
Nel fare questo punto bisogna tenere a mente i seguenti punti:
- i piatti da aggiungere al carrello devono essere tutti appartenenti allo stesso ordine
- per ogni singolo piatto bisognerà indicare la quantità e un campo di note
- i piatti vanno aggiunti utilizzando il menù del ristorante (da questa pagina quindi si può fare l'aggiunta al carrello, ma solo se si sta visualizzando il menù dello stesso ristorante o se non si ha nulla nel carrello
- dal carrello poi si potrà effettuare il pagamento e inviare così una volta per tutte l'ordine (richiederà un'api backend per salvare i vari dati dell'ordine)

**Comment by MarcoBione** [comment]
Branch aperto : 
git fetch origin
git checkout 26-realizzare-carrello

**Comment by MarcoBione** [comment]
Aggiunto un layout base con il controllo presenza dati nella tabella..
layout iniziale per vedere il corretto funzionamento, ovviamente ci sarà da rifare il layout quando il funzionamento sarà appurato

**Comment by totarochristian** [comment]
Opzioni aggiuntive:
- sistemare il numero sopra l'icona del carrello in base al numero di piatti nel carrello
- cambiare il colore sotto l'icona del carrello in base al quantitativo di elementi nel carrello (se vuoto un colore, altrimenti un altro)

MOLTO IMPORTANTE:
I piatti nel carrello devono essere per forza relativi allo stesso ristorante!!!!

**Comment by totarochristian** [comment]
La base del carrello è stata realizzata.

Bisogna aggiungere il cambio del numero di elementi nel carrello e il nome del ristorante nel titolo del carrello.
