### ISSUE TITLE
Sistemare il menù di navigazione

### ISSUE THREAD

**Issue by totarochristian** [MarcoBione/hungry-frontoffice#27]
Bisogna sistemare il menù di navigazione perchè deve essere possibile sruttarlo per tornare all'homepage

**Comment by MarcoBione** [comment]
Presa in carico,
Branch aperto : 

git fetch origin
git checkout 27-sistemare-il-menù-di-navigazione

**Comment by MarcoBione** [comment]
Aggiunta voce "Home" nel menu a tendina in modo tale da poter tornare alla home in qualsiasi momento
