### ISSUE TITLE
Preparare il footer

### ISSUE THREAD

**Issue by totarochristian** [MarcoBione/hungry-frontoffice#4]

**Comment by MarcoBione** [comment]
Presa in carico da me

Aperto branch:

git fetch origin
git checkout 4-preparare-il-footer

**Comment by MarcoBione** [comment]
Footer aggiunto
Fixare i layer logo e lista.. il logo rimane sopra la lista e non permette ai link di essere premuti

**Comment by MarcoBione** [comment]
Footer fixato e concluso
utilizzati effetti di hover per la colorazione dei link una volta sopra con il mouse
z-index per le liste di links
