### ISSUE TITLE
Preparare la pagina di dettaglio della singola tipologia di ristorante cliccata, con la ricerca avanzata posta sopra i ristoranti

### ISSUE THREAD

**Issue by totarochristian** [MarcoBione/hungry-frontoffice#7]

**Comment by MarcoBione** [comment]
Creazione della pagina principale di dettaglio contente :

- un filtro avanzato in alto
- il titolo del contenuto con il numero di risultati
-il contenuto con le card inerenti alla ricerca

- header + footer sempre visibili in pagina

Branch aperto :
git fetch origin
git checkout 7-preparare-la-pagina-di-dettaglio-della-singola-tipologia-di-ristorante-cliccata-con-la-ricerca-avanzata-posta-sopra-i-ristoranti

**Comment by totarochristian** [comment]
Guarda il nuovo milestone che approfondisce questa pagina
